#!/bin/sh

[ -e ssh.out ] && rm ssh.out
while true ; do
  read -p "sdn@blah: " line
  if [ "$1" == "-i" ] ; then
    echo "yep $line" >> ssh.out
  else
    echo $line >> ssh.out 
  fi
  #if [ $(echo $line|grep -c exit) -gt 0 ] ; then
  #  exit
  #fi
done
