# NOTE:  This Dockerfile is used to build a test shifter image.  The image can be used
#        to mimic a system (login node) that would have shifter installed.
#        This is only used for testing purposes.
#        It runs munge and sshd which would normally be a bad idea for a container.
#
#        If you are looking to build an image for the gateway.  Look at the Dockerfile
#        in imagegw/src.

FROM ubuntu:14.04
MAINTAINER Shane Canon <scanon@lbl.gov>

# Thanks to Sven Dowideit <SvenDowideit@docker.com>
# for a Dockerfile that configured ssh

# Install requirements to build shifter, run munge, and openssh
RUN apt-get update && \
       apt-get install -y gcc autoconf make libtool g++ munge libmunge-dev  \
       libcurl4-openssl-dev libjson-c-dev build-essential openssh-server libcap-dev \
       curl openssh-client sudo python-pip && \
    mkdir /var/run/sshd && \
    mkdir /var/run/munge && \
    chown munge /var/run/munge && \
    echo 'root:lookatmenow' | chpasswd && \
    sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "export VISIBLE=now" >> /etc/profile

ADD requirements.txt /tmp/

RUN \
   pip install -r /tmp/requirements.txt

ENV NOTVISIBLE "in users profile"

ADD . /src/
RUN cd /src/ && python ./setup.py install

# Fix up perms and other things
RUN \
    cp /src/test/nersc_sdn.conf.test /etc/nersc_sdn.conf && \
    cp /src/test/squeue.mock /usr/bin/squeue && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    echo "   StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
    chmod 755 /var/log/

ENTRYPOINT [ "/src/test/entrypoint.sh" ]
